version: "3.8"

services:
  # --- 1. DATABASE SERVICE ---
  db_service:
    image: mysql:8.0
    container_name: db_F6
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: rootpassword
    # volumes
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    # Network
    networks:
      - sakuku_net

  # --- 2. APP SERVICE ---
  app_service:
    build: ./app
    container_name: app_${GROUP_NAME}
    restart: always
    expose:
      - "3000"
    environment:
      - DB_HOST=db_service
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - APP_PORT=3000
    depends_on:
      - db_service
    # Network
    networks:
      - sakuku_net

  # --- 3. NGINX SERVICE ---
  nginx_service:
    image: nginx:alpine
    container_name: nginx_${GROUP_NAME}
    restart: always
    ports:
      - "2586:80"
    depends_on:
      - app_service
    # Network
    networks:
      - sakuku_net
    # volumes
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

#--- VOLUMES AND NETWORKS ---
volumes:
  db_data:

networks:
  sakuku_net: